<?xml version="1.0"?>
<robot xmlns:xacro="hhttp://www.ros.org/wiki/xacro" name="elderbot">
  <xacro:include filename="robotcore.xacro" />

  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <left_joint>left_rear_wheel_joint</left_joint>
      <right_joint>right_rear_wheel_joint</right_joint>

      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <ros>
        <remapping>cmd_vel:=/cmd_vel</remapping>
        <remapping>odom:=/odom</remapping>
      </ros>
      
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>

      <publishOdom>true</publishOdom>
      <publishTf>true</publishTf>
      <publishWheelJointState>true</publishWheelJointState>

      <legacyMode>false</legacyMode>
    </plugin>
    
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>50</update_rate>
      <joint_name>left_front_wheel_joint</joint_name>
      <joint_name>right_front_wheel_joint</joint_name>
      <joint_name>left_rear_wheel_joint</joint_name>
      <joint_name>right_rear_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>
