<?xml version="1.0"?>
<robot xmlns:xacro="hhttp://www.ros.org/wiki/xacro" name="elderbot">
  <xacro:include filename="robotcore.xacro" />

  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <update_rate>10</update_rate>
      <left_joint>left_rear_wheel_joint</left_joint>
      <right_joint>right_rear_wheel_joint</right_joint>

      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <publishOdomTF>true</publishOdomTF>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
      
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf> 
      <ros>
          <namespace>/</namespace>
          <remapping>cmd_vel:=cmd_vel</remapping>
          <remapping>odom:=odom</remapping>
      </ros>
      
    </plugin>
    
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>50</update_rate>
      <joint_name>left_front_wheel_joint</joint_name>
      <joint_name>right_front_wheel_joint</joint_name>
      <joint_name>left_rear_wheel_joint</joint_name>
      <joint_name>right_rear_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>
