slam_toolbox:
  ros__parameters:
    # Tên các frame
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint

    # Tham số cảm biến
    scan_topic: /scan
    use_scan_matching: true
    max_laser_range: 12.0

    # Các thông số khác
    solver_plugin: "solver_plugins::CeresSolver"
    mode: "mapping"
    map_update_interval: 2.0
    resolution: 0.05